/*
 * Per-species action ID enums — generated by tools/dump_species_actions.py
 *
 * Action IDs are the u32 values an action_decided override may return to
 * pick a behavior the engine knows. Unknown IDs use the SPECIES_ACTION_0x????
 * naming pattern; replace with descriptive names as they get RE'd. Durations
 * (u16 ticks at 30 Hz) are not exposed here — they're a per-entry property of
 * the species table, fixed by the engine.
 *
 * SMALL monsters (popo/anteka) use the species data table +0x0C action list.
 * BIG monsters (Tigrex/Giadrome) have an empty +0x0C; their action list lives
 * elsewhere (per CLAUDE.md §19g.3 the dispatcher swaps entity+0x640 at runtime
 * from a global table 0x09BD38F0). Extracting it needs the monster live; deferred.
 *
 * Regenerate after a species data table change:
 *   PYTHONPATH=src python tools/dump_species_actions.py
 */
#ifndef MHFU_AI_ACTIONS_H
#define MHFU_AI_ACTIONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* popo (type 0x46) — 13 actions */
#define POPO_ACTION_0x0060               0x0060u  /* slot 0, dur 9000 (300.0s) */
#define POPO_ACTION_0x0061               0x0061u  /* slot 1, dur 3600 (120.0s) */
#define POPO_ACTION_0x0064               0x0064u  /* slot 2, dur 9000 (300.0s) */
#define POPO_ACTION_0x0070               0x0070u  /* slot 3, dur 9000 (300.0s) */
#define POPO_ACTION_0x0071               0x0071u  /* slot 4, dur 9000 (300.0s) */
#define POPO_ACTION_0x0073               0x0073u  /* slot 5, dur 5400 (180.0s) */
#define POPO_ACTION_0x0074               0x0074u  /* slot 6, dur 9000 (300.0s) */
#define POPO_ACTION_0x0076               0x0076u  /* slot 7, dur 5400 (180.0s) */
#define POPO_ACTION_0x009C               0x009Cu  /* slot 8, dur 5400 (180.0s) */
#define POPO_ACTION_0x009D               0x009Du  /* slot 9, dur 5400 (180.0s) */
#define POPO_ACTION_0x009E               0x009Eu  /* slot 10, dur 9000 (300.0s) */
#define POPO_ACTION_0x009F               0x009Fu  /* slot 11, dur 9000 (300.0s) */
#define POPO_ACTION_0x00A0               0x00A0u  /* slot 12, dur 5400 (180.0s) */

/* anteka (type 0x45) — 40 actions */
#define ANTEKA_ACTION_0x0043             0x0043u  /* slot 0, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0044             0x0044u  /* slot 1, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0045             0x0045u  /* slot 2, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0047             0x0047u  /* slot 3, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0048             0x0048u  /* slot 4, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0049             0x0049u  /* slot 5, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x004B             0x004Bu  /* slot 6, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x0457             0x0457u  /* slot 7, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x0071             0x0071u  /* slot 8, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0072             0x0072u  /* slot 9, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x008C             0x008Cu  /* slot 10, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x008D             0x008Du  /* slot 11, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x008E             0x008Eu  /* slot 12, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x008F             0x008Fu  /* slot 13, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0091             0x0091u  /* slot 14, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0094             0x0094u  /* slot 15, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0095             0x0095u  /* slot 16, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0096             0x0096u  /* slot 17, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00A6             0x00A6u  /* slot 18, dur 14400 (480.0s) */
#define ANTEKA_ACTION_0x00A7             0x00A7u  /* slot 19, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00C9             0x00C9u  /* slot 20, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00CA             0x00CAu  /* slot 21, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00CB             0x00CBu  /* slot 22, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00D2             0x00D2u  /* slot 23, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00D3             0x00D3u  /* slot 24, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00D4             0x00D4u  /* slot 25, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x04C1             0x04C1u  /* slot 26, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00DE             0x00DEu  /* slot 27, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00DF             0x00DFu  /* slot 28, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x00E2             0x00E2u  /* slot 29, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00E4             0x00E4u  /* slot 30, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00E7             0x00E7u  /* slot 31, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00E9             0x00E9u  /* slot 32, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x00EA             0x00EAu  /* slot 33, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00EB             0x00EBu  /* slot 34, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00EC             0x00ECu  /* slot 35, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00EF             0x00EFu  /* slot 36, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00F0             0x00F0u  /* slot 37, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00F5             0x00F5u  /* slot 38, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00F6             0x00F6u  /* slot 39, dur 7200 (240.0s) */

/* tigrex (0x4B) — no action list available */

/* giadrome (0x4D) — no action list available */

/* Predicate: is `id` a valid action for `species` (member of its list)? */
int mhfu_action_is_valid(uint8_t monster_type, uint32_t action_id);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MHFU_AI_ACTIONS_H */
