/*
 * Per-species action ID enums — generated by tools/dump_species_actions.py
 *
 * Action IDs are the u32 values an action_decided override may return to
 * pick a behavior the engine knows. Unknown IDs use the SPECIES_ACTION_0x????
 * naming pattern; replace with descriptive names as they get RE'd. Durations
 * (u16 ticks at 30 Hz) are not exposed here — they're a per-entry property of
 * the species table, fixed by the engine.
 *
 * SMALL monsters (popo/anteka) use the species data table +0x0C action list.
 * GIADROME (also classified 'big' in quest UI but with small-mon AI shape) DOES
 * have a +0x0C action list — runtime-allocated, identical record format.
 * TIGREX is the true outlier: its +0x0C is hitzone data, not an action list.
 * vt[8] returns POINTERS into the probability table at entity+0x1AC for tigrex,
 * so an action_id enum doesn't apply cleanly — TIGREX_ACTION_* macros are omitted.
 *
 * Regenerate after a species data table change:
 *   PYTHONPATH=src python tools/dump_species_actions.py
 */
#ifndef MHFU_AI_ACTIONS_H
#define MHFU_AI_ACTIONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* popo (type 0x46) — 13 actions */
#define POPO_ACTION_0x0060               0x0060u  /* slot 0, dur 9000 (300.0s) */
#define POPO_ACTION_0x0061               0x0061u  /* slot 1, dur 3600 (120.0s) */
#define POPO_ACTION_0x0064               0x0064u  /* slot 2, dur 9000 (300.0s) */
#define POPO_ACTION_0x0070               0x0070u  /* slot 3, dur 9000 (300.0s) */
#define POPO_ACTION_0x0071               0x0071u  /* slot 4, dur 9000 (300.0s) */
#define POPO_ACTION_0x0073               0x0073u  /* slot 5, dur 5400 (180.0s) */
#define POPO_ACTION_0x0074               0x0074u  /* slot 6, dur 9000 (300.0s) */
#define POPO_ACTION_0x0076               0x0076u  /* slot 7, dur 5400 (180.0s) */
#define POPO_ACTION_0x009C               0x009Cu  /* slot 8, dur 5400 (180.0s) */
#define POPO_ACTION_0x009D               0x009Du  /* slot 9, dur 5400 (180.0s) */
#define POPO_ACTION_0x009E               0x009Eu  /* slot 10, dur 9000 (300.0s) */
#define POPO_ACTION_0x009F               0x009Fu  /* slot 11, dur 9000 (300.0s) */
#define POPO_ACTION_0x00A0               0x00A0u  /* slot 12, dur 5400 (180.0s) */

/* anteka (type 0x45) — 40 actions */
#define ANTEKA_ACTION_0x0043             0x0043u  /* slot 0, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0044             0x0044u  /* slot 1, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0045             0x0045u  /* slot 2, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0047             0x0047u  /* slot 3, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0048             0x0048u  /* slot 4, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x0049             0x0049u  /* slot 5, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x004B             0x004Bu  /* slot 6, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x0457             0x0457u  /* slot 7, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x0071             0x0071u  /* slot 8, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0072             0x0072u  /* slot 9, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x008C             0x008Cu  /* slot 10, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x008D             0x008Du  /* slot 11, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x008E             0x008Eu  /* slot 12, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x008F             0x008Fu  /* slot 13, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0091             0x0091u  /* slot 14, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0094             0x0094u  /* slot 15, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x0095             0x0095u  /* slot 16, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x0096             0x0096u  /* slot 17, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00A6             0x00A6u  /* slot 18, dur 14400 (480.0s) */
#define ANTEKA_ACTION_0x00A7             0x00A7u  /* slot 19, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00C9             0x00C9u  /* slot 20, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00CA             0x00CAu  /* slot 21, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00CB             0x00CBu  /* slot 22, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00D2             0x00D2u  /* slot 23, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00D3             0x00D3u  /* slot 24, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00D4             0x00D4u  /* slot 25, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x04C1             0x04C1u  /* slot 26, dur 3600 (120.0s) */
#define ANTEKA_ACTION_0x00DE             0x00DEu  /* slot 27, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00DF             0x00DFu  /* slot 28, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x00E2             0x00E2u  /* slot 29, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00E4             0x00E4u  /* slot 30, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00E7             0x00E7u  /* slot 31, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00E9             0x00E9u  /* slot 32, dur 7200 (240.0s) */
#define ANTEKA_ACTION_0x00EA             0x00EAu  /* slot 33, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00EB             0x00EBu  /* slot 34, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00EC             0x00ECu  /* slot 35, dur 9000 (300.0s) */
#define ANTEKA_ACTION_0x00EF             0x00EFu  /* slot 36, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00F0             0x00F0u  /* slot 37, dur 5400 (180.0s) */
#define ANTEKA_ACTION_0x00F5             0x00F5u  /* slot 38, dur 10800 (360.0s) */
#define ANTEKA_ACTION_0x00F6             0x00F6u  /* slot 39, dur 7200 (240.0s) */

/* tigrex (0x4B) — no action list available */

/* giadrome (type 0x4D) — 34 actions */
#define GIADROME_ACTION_0x0060           0x0060u  /* slot 0, dur 9000 (300.0s) */
#define GIADROME_ACTION_0x0061           0x0061u  /* slot 1, dur 9000 (300.0s) */
#define GIADROME_ACTION_0x044B           0x044Bu  /* slot 2, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x044C           0x044Cu  /* slot 3, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x0070           0x0070u  /* slot 4, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x0459           0x0459u  /* slot 5, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x0073           0x0073u  /* slot 6, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x045C           0x045Cu  /* slot 7, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x045E           0x045Eu  /* slot 8, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x008D           0x008Du  /* slot 9, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x0476           0x0476u  /* slot 10, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x0477           0x0477u  /* slot 11, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x0091           0x0091u  /* slot 12, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x047D           0x047Du  /* slot 13, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x00C9           0x00C9u  /* slot 14, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00CA           0x00CAu  /* slot 15, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x04B3           0x04B3u  /* slot 16, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x04B7           0x04B7u  /* slot 17, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x00D3           0x00D3u  /* slot 18, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00D4           0x00D4u  /* slot 19, dur 9000 (300.0s) */
#define GIADROME_ACTION_0x04C2           0x04C2u  /* slot 20, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x04C3           0x04C3u  /* slot 21, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x00DE           0x00DEu  /* slot 22, dur 9000 (300.0s) */
#define GIADROME_ACTION_0x00DF           0x00DFu  /* slot 23, dur 9000 (300.0s) */
#define GIADROME_ACTION_0x00E1           0x00E1u  /* slot 24, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00E2           0x00E2u  /* slot 25, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00E4           0x00E4u  /* slot 26, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00E6           0x00E6u  /* slot 27, dur 3600 (120.0s) */
#define GIADROME_ACTION_0x00E7           0x00E7u  /* slot 28, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00F9           0x00F9u  /* slot 29, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00FB           0x00FBu  /* slot 30, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00FC           0x00FCu  /* slot 31, dur 7200 (240.0s) */
#define GIADROME_ACTION_0x00FD           0x00FDu  /* slot 32, dur 5400 (180.0s) */
#define GIADROME_ACTION_0x00FE           0x00FEu  /* slot 33, dur 7200 (240.0s) */

/* Predicate: is `id` a valid action for `species` (member of its list)? */
int mhfu_action_is_valid(uint8_t monster_type, uint32_t action_id);

#ifdef __cplusplus
} /* extern "C" */
#endif


/* tigrex VT8_INPUT macros — observed live (regenerate with tools/dump_tigrex_inputs.py) */
/* vt8_input values for Tigrex are STABLE across runs (keyed by species
 * probability table). The ENGINE_ID pointer vt[8] returns for each is NOT
 * stable — it depends on per-run RAM allocation. Use these macros to MATCH
 * on the input in an action_decided callback; for OVERRIDE, cache the ptr
 * the engine returns for the input you want and re-return it later. */
/* 50 action inputs + 4 probe inputs */
#define TIGREX_VT8_INPUT_0x0001    0x0001u  /* observed -> 0x094270F8 */
#define TIGREX_VT8_INPUT_0x00C9    0x00C9u  /* observed -> 0x094D69F4 */
#define TIGREX_VT8_INPUT_0x0191    0x0191u  /* observed -> 0x09503F38 */
#define TIGREX_VT8_INPUT_0x03E9    0x03E9u  /* observed -> 0x094270F8 */
#define TIGREX_VT8_INPUT_0x03EB    0x03EBu  /* observed -> 0x09429E54 */
#define TIGREX_VT8_INPUT_0x03ED    0x03EDu  /* observed -> 0x0942F268 */
#define TIGREX_VT8_INPUT_0x03EE    0x03EEu  /* observed -> 0x094310C0 */
#define TIGREX_VT8_INPUT_0x03F3    0x03F3u  /* observed -> 0x0943C254 */
#define TIGREX_VT8_INPUT_0x03F6    0x03F6u  /* observed -> 0x09443220 */
#define TIGREX_VT8_INPUT_0x03F7    0x03F7u  /* observed -> 0x0944466C */
#define TIGREX_VT8_INPUT_0x03FA    0x03FAu  /* observed -> 0x09448E58 */
#define TIGREX_VT8_INPUT_0x03FB    0x03FBu  /* observed -> 0x0944E044 */
#define TIGREX_VT8_INPUT_0x03FF    0x03FFu  /* observed -> 0x094591E0 */
#define TIGREX_VT8_INPUT_0x0406    0x0406u  /* observed -> 0x0945B05C */
#define TIGREX_VT8_INPUT_0x0407    0x0407u  /* observed -> 0x0945C570 */
#define TIGREX_VT8_INPUT_0x0408    0x0408u  /* observed -> 0x0945DADC */
#define TIGREX_VT8_INPUT_0x0438    0x0438u  /* observed -> 0x094C4C04 */
#define TIGREX_VT8_INPUT_0x0442    0x0442u  /* observed -> 0x094CC668 */
#define TIGREX_VT8_INPUT_0x04B1    0x04B1u  /* observed -> 0x094D69F4 */
#define TIGREX_VT8_INPUT_0x04B3    0x04B3u  /* observed -> 0x094D7628 */
#define TIGREX_VT8_INPUT_0x04B5    0x04B5u  /* observed -> 0x094D85D4 */
#define TIGREX_VT8_INPUT_0x04B6    0x04B6u  /* observed -> 0x094D8DB8 */
#define TIGREX_VT8_INPUT_0x04BB    0x04BBu  /* observed -> 0x094DBAF8 */
#define TIGREX_VT8_INPUT_0x04BE    0x04BEu  /* observed -> 0x094DD524 */
#define TIGREX_VT8_INPUT_0x04BF    0x04BFu  /* observed -> 0x094DD8F4 */
#define TIGREX_VT8_INPUT_0x04C2    0x04C2u  /* observed -> 0x094DE724 */
#define TIGREX_VT8_INPUT_0x04C3    0x04C3u  /* observed -> 0x094DF088 */
#define TIGREX_VT8_INPUT_0x04C7    0x04C7u  /* observed -> 0x094E1EE0 */
#define TIGREX_VT8_INPUT_0x04C8    0x04C8u  /* observed -> 0x094E22B8 */
#define TIGREX_VT8_INPUT_0x04C9    0x04C9u  /* observed -> 0x094E2DF8 */
#define TIGREX_VT8_INPUT_0x04CE    0x04CEu  /* observed -> 0x094E3670 */
#define TIGREX_VT8_INPUT_0x04CF    0x04CFu  /* observed -> 0x094E3A60 */
#define TIGREX_VT8_INPUT_0x04D0    0x04D0u  /* observed -> 0x094E3F18 */
#define TIGREX_VT8_INPUT_0x0500    0x0500u  /* observed -> 0x094FE758 */
#define TIGREX_VT8_INPUT_0x050A    0x050Au  /* observed -> 0x09500760 */
#define TIGREX_VT8_INPUT_0x0579    0x0579u  /* observed -> 0x09503F38 */
#define TIGREX_VT8_INPUT_0x057B    0x057Bu  /* observed -> 0x095046B4 */
#define TIGREX_VT8_INPUT_0x057D    0x057Du  /* observed -> 0x09505258 */
#define TIGREX_VT8_INPUT_0x057E    0x057Eu  /* observed -> 0x09505674 */
#define TIGREX_VT8_INPUT_0x0583    0x0583u  /* observed -> 0x09507374 */
#define TIGREX_VT8_INPUT_0x0586    0x0586u  /* observed -> 0x095087DC */
#define TIGREX_VT8_INPUT_0x0587    0x0587u  /* observed -> 0x09508A0C */
#define TIGREX_VT8_INPUT_0x058A    0x058Au  /* observed -> 0x09509254 */
#define TIGREX_VT8_INPUT_0x058B    0x058Bu  /* observed -> 0x0950985C */
#define TIGREX_VT8_INPUT_0x058F    0x058Fu  /* observed -> 0x0950AF7C */
#define TIGREX_VT8_INPUT_0x0596    0x0596u  /* observed -> 0x0950B1EC */
#define TIGREX_VT8_INPUT_0x0597    0x0597u  /* observed -> 0x0950B45C */
#define TIGREX_VT8_INPUT_0x0598    0x0598u  /* observed -> 0x0950B734 */
#define TIGREX_VT8_INPUT_0x05C8    0x05C8u  /* observed -> 0x0951A778 */
#define TIGREX_VT8_INPUT_0x05D2    0x05D2u  /* observed -> 0x0951BF8C */

/* Probe inputs (vt[8] returns 0 — used by engine to test if slot exists) */
#define TIGREX_VT8_PROBE_0x0000    0x0000u
#define TIGREX_VT8_PROBE_0x00C8    0x00C8u
#define TIGREX_VT8_PROBE_0x0190    0x0190u
#define TIGREX_VT8_PROBE_0x0258    0x0258u

/* Friendly-name aliases — hand-curated mapping (see
 * tools/dump_tigrex_inputs.py:TIGREX_INPUT_LABELS). Emitted
 * unconditionally so mods can match on these even when the raw
 * VT8_INPUT macro for the input wasn't snooped this run. */
#define TIGREX_ANGRY_BITE_FORWARD       0x05A1u  /* not observed this run */
#define TIGREX_ANGRY_BRIEFHALT          0x057Au  /* not observed this run */
#define TIGREX_ANGRY_CHARGE             0x0589u  /* not observed this run */
#define TIGREX_ANGRY_CHARGE_STOP        0x0581u  /* not observed this run */
#define TIGREX_ANGRY_CHARGE_TURN        0x0584u  /* not observed this run */
#define TIGREX_ANGRY_JUMP_FORWARD       0x05A7u  /* not observed this run */
#define TIGREX_ANGRY_JUMP_LAND          0x05A8u  /* not observed this run */
#define TIGREX_ANGRY_SPIN               0x05A3u  /* not observed this run */
#define TIGREX_ANGRY_THROWROCKS         0x05A5u  /* not observed this run */
#define TIGREX_ANGRY_TURN_LEFT          0x0580u  /* not observed this run */
#define TIGREX_ANGRY_TURN_RIGHT         0x057Fu  /* not observed this run */
#define TIGREX_ENTERMAP_FALLDOWN        0x0583u
#define TIGREX_ENTERMAP_FALLDOWN_LAND   0x058Bu
#define TIGREX_IDLE_STAND               0x0598u
#define TIGREX_IDLE_SUSPICIOUS          0x05C8u
#define TIGREX_IDLE_TURN_LEFT           0x057Eu
#define TIGREX_IDLE_WALKSTRAIGHT        0x057Bu

#endif /* MHFU_AI_ACTIONS_H */
