#!/usr/bin/env python3
"""Embed a .lua script as a C const char[] header.

Source of truth = the .lua file. lua_host #includes the generated .h and
runs the bytes (until Phase 3 ships memstick file loading). Regenerate after
editing a .lua:  python3 tools/embed_lua.py <in.lua> <out.lua.h>
"""
import os
import sys


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: embed_lua.py <in.lua> <out.lua.h>\n")
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()

    stem = os.path.splitext(os.path.basename(src))[0]
    sym = "k_lua_" + "".join(c if c.isalnum() else "_" for c in stem)
    guard = "MHFU_EMBED_" + sym.upper() + "_H"

    # Emit as a C string literal with 3-digit octal escapes: never narrows
    # (unlike a >127 int in a braced char[] under C++), handles any byte, and
    # the literal's implicit NUL terminator is what luaL_loadstring wants.
    lines = [
        "/* GENERATED by tools/embed_lua.py from %s -- do not edit. */"
        % os.path.basename(src),
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "static const char %s[] =" % sym,
    ]
    chunk = []
    for b in data:
        chunk.append("\\%03o" % b)
        if len(chunk) >= 20:
            lines.append('  "%s"' % "".join(chunk))
            chunk = []
    if chunk:
        lines.append('  "%s"' % "".join(chunk))
    lines.append("  ;")
    lines.append("")
    lines.append("#endif /* %s */" % guard)
    lines.append("")

    with open(dst, "w") as f:
        f.write("\n".join(lines))
    sys.stderr.write("embed_lua: %s -> %s (%d bytes)\n" % (src, dst, len(data)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
